### PR TITLE
Sparse poa fix

### PR DESCRIPTION
**Pull request by dalexander**
Don't merge this yet, I need to do some benchmarks.

### CODE REVIEW

**Comment by dalexander** [comment]
OK, I'm happy with this now. 

Here are some benchmark numbers:


## Benchmark before and after: 2kb ET pbell

```sh
        vm0902-def14:2kET $ /usr/bin/time -v /home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-master-d0431bf6b --force  --numThreads=1 out.bam 102.subreads.bam
        Command being timed: "/home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-master-d0431bf6b --force --numThreads=1 out.bam 102.subreads.bam"
        *User time (seconds): 6.73*
        *Maximum resident set size (kbytes): 258060*


        vm0902-def14:2kET $ /usr/bin/time -v /home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-sparse-poa-fix-a117101 --force  --numThreads=1 out.bam 102.subreads.bam
        Command being timed: "/home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-sparse-poa-fix-a117101 --force --numThreads=1 out.bam 102.subreads.bam"
        *User time (seconds): 2.89*
        *Maximum resident set size (kbytes): 41676*
```

## Benchmark before and after: IsoSeq-representative use case

   /home/UNIXHOME/etseng/projects2016/TimSmith_pig/smrtpipe/thymus/m150914_021240_42132_c100892822550000001823205904231644_s1_p0.subreads.bam
   First 200 ZMWs...

```sh
   (VE)login14-biofx03:TimSmith-Pig $  /usr/bin/time -v /home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-master-d0431bf6b --minPasses 1  --maxLength 15000 --minPredictedAccuracy 0.80  --numThreads=1 --force --reportFile=report.csv  --zmws=0-200  out.bam m150914_021240_42132_c100892822550000001823205904231644_s1_p0.subreads.bam
   Command being timed: "/home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-master-d0431bf6b --minPasses 1 --maxLength 15000 --minPredictedAccuracy 0.80 --numThreads=1 --force --reportFile=report.csv --zmws=0-200 out.bam m150914_021240_42132_c100892822550000001823205904231644_s1_p0.subreads.bam"
   *User time (seconds): 197.25*
   *Maximum resident set size (kbytes): 2132128*  == 2GB

   (VE)login14-biofx03:TimSmith-Pig $  /usr/bin/time -v /home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-sparse-poa-fix-a117101 --minPasses 1  --maxLength 15000 --minPredictedAccuracy 0.80  --numThreads=1 --force --reportFile=report.csv  --zmws=0-200  out.bam m150914_021240_42132_c100892822550000001823205904231644_s1_p0.subreads.bam
   Command being timed: "/home/UNIXHOME/dalexander/Projects/git/pbccs/bin/ccs-sparse-poa-fix-a117101 --minPasses 1 --maxLength 15000 --minPredictedAccuracy 0.80 --numThreads=1 --force --reportFile=report.csv --zmws=0-200 out.bam m150914_021240_42132_c100892822550000001823205904231644_s1_p0.subreads.bam"
   *User time (seconds): 136.43*
   *Maximum resident set size (kbytes): 205260* == 200MB
```

**Comment by dalexander** [comment]
@nlhepler, what do you think, shall we merge?

**Comment by nlhepler** [comment]
Aye! Do you want to do the honors? =)

**Comment by dalexander** [comment]
will do as soon as test passes... 

FYI pruning is not yet implemented, there's more gain to be had there at some point.

**Pull request merged**
