### PR TITLE
No pollution

### PR DESCRIPTION
**Pull request by armintoepfer**
Do not generate config file into include/, rather build/generated/. Do not export test executable outside build directory. Remove double includes.

### CODE REVIEW

**Comment by nlhepler** [comment]
Nice! Rebase please

**Comment by nlhepler** [comment]
Also please update the `check` target too please.

**Comment by nlhepler** [comment]
And, as before, if you want the ci tests to pass you'll need to push to a branch on PacificBiosciences/ConsensusCore2. It needs access to the gh token.

**Comment by armintoepfer** [comment]
Will open a new PR from within this repo

**Pull request closed without merging**
