### PR TITLE
Cache The Maximum Value

### PR DESCRIPTION
**Pull request by evolvedmicrobe**
This change improves the speed from ~ 4.7 seconds to ~3.6 seconds (~25%
less time) on the test case given in Bugzilla # 32220.

The optimization is to avoid a second pass through the sparse matrix
vector to find the max value for normalization, but to collect that
value during the first pass and then pass it in to the finish editing
column.

Assuming this passes tests, for review by @dalexander

### CODE REVIEW

**Comment by dalexander** [comment]
is this a performance improvement generally?

**Comment by evolvedmicrobe** [comment]
It didn't seem to really affect the test case timings much, so I think it is only useful when the sparse matrix  has large bands in it.

**Comment by evolvedmicrobe** [comment]
It seems to be a wash on regular data, for example the test data we have:
* Old time - 1 
real	0m46.026s
user	5m22.832s
sys	0m8.426s

* New time - 1
real	0m46.686s
user	5m19.562s
sys	0m8.690s

* Old time - 2

real	0m46.489s
user	5m23.152s
sys	0m8.360s

* New time - 2

real	0m45.580s
user	5m16.805s
sys	0m8.540s

**Comment by nlhepler** [comment]
might still be worth it to reduce the runtime cost on pathological data. there will always be some.

**Comment by evolvedmicrobe** [comment]
Well, I think your recent set of changes covered all the non-pathological cases! We seem to be well under the 1 second per ZMW target we were aiming for, so I figured from here on out it would be better to spend our time on outliers than further optimizing the code (and removing those branches by adding sentinels will not be fun...)

**Pull request merged**
